language: java

jdk:
  - oraclejdk8

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y python
  - sudo pip install Pillow
  - sudo pip install numpy
  - sudo pip install matplotlib

script:
  - ./gradlew clean assemble check -Dpre-dex=false --stacktrace
  - ./gradlew generateImages --stacktrace

after_success:
  - ./gradlew jacocoTestReport coveralls --stacktrace

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: true

cache:
  directories:
    - $HOME/.gradle
    - $HOME/.cache/pip

